[2025-01-14 17:08:58] [info] asio async_connect error: asio.system:61 (Connection refused)
[2025-01-14 17:08:58] [info] Error getting remote endpoint: asio.system:22 (Invalid argument)
[2025-01-14 17:08:58] [error] handle_connect error: Connection refused
